refactor components without BEM CSS pattern
backstage-ui/backstage-ui pull request #12
Opened 2017-06-20 18:35 UTC by richardkevin

2017-06-20 20:40 UTC, vierno requested changes
Please, remove the nested class rules.

2017-06-20 22:41 UTC, vierno requested changes

2017-06-20 22:41 UTC, vierno commented on scss/components/_breadcrumbs.scss
> +        &--link {
Link should be an element, not a modifier.

2017-06-20 22:41 UTC, vierno commented on scss/components/_notification.scss
> +    .bs-ui-notification__text {
This element should not be nested

2017-06-20 22:41 UTC, vierno commented on scss/components/_table.scss
> +        &__tr {
Could we use more meaningful names instead of the tags as classes?

2017-06-20 22:41 UTC, vierno commented on scss/components/_table.scss
> +            &.selected {
Fix me?

2017-06-20 23:00 UTC, marcelometal requested changes

2017-06-20 23:00 UTC, marcelometal commented on scss/components/_form-controls.scss
should be used @extend %font-14?

2017-06-21 21:39 UTC, vierno approved these changes

2017-06-22 15:00 UTC, marcelometal approved these changes

2017-06-22 17:04 UTC, ricobl requested changes
Hey @richardkevin! Can you please review my comments?

Also, looks like there is no change in dependencies but the `yarn.lock` has changed. I believe it should be unchangend in this PR.

2017-06-22 17:04 UTC, ricobl commented on scss/components/_form_controls_input.scss
> +        &--textarea {
This should be an element, not a modifier...

2017-06-22 17:04 UTC, ricobl commented on scss/components/_form_controls_input.scss
> +            &.bs-ui-form-control__field {
Is it required to have two classes here?

2017-06-22 17:04 UTC, ricobl commented on scss/components/_options.scss
> +        &--link {
This should be an element, not a modifier.

2017-06-22 17:04 UTC, ricobl commented on scss/components/_table.scss
> +                .bs-ui-table__span:before {
Can we find a better name than `span`?

2017-06-22 18:34 UTC, merged